/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AfleveringenRouteImport } from './routes/afleveringen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatingsIndexRouteImport } from './routes/ratings.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RatingsSlugRouteImport } from './routes/ratings.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogBesteGolfbanenRondAntwerpenRouteImport } from './routes/blog.beste-golfbanen-rond-antwerpen'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AfleveringenRoute = AfleveringenRouteImport.update({
  id: '/afleveringen',
  path: '/afleveringen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsIndexRoute = RatingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RatingsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const RatingsSlugRoute = RatingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RatingsRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBesteGolfbanenRondAntwerpenRoute =
  BlogBesteGolfbanenRondAntwerpenRouteImport.update({
    id: '/beste-golfbanen-rond-antwerpen',
    path: '/beste-golfbanen-rond-antwerpen',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afleveringen': typeof AfleveringenRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/mcp': typeof McpRoute
  '/ratings': typeof RatingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/beste-golfbanen-rond-antwerpen': typeof BlogBesteGolfbanenRondAntwerpenRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ratings/': typeof RatingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afleveringen': typeof AfleveringenRoute
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/beste-golfbanen-rond-antwerpen': typeof BlogBesteGolfbanenRondAntwerpenRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/ratings': typeof RatingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afleveringen': typeof AfleveringenRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/mcp': typeof McpRoute
  '/ratings': typeof RatingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/beste-golfbanen-rond-antwerpen': typeof BlogBesteGolfbanenRondAntwerpenRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ratings/': typeof RatingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afleveringen'
    | '/blog'
    | '/contact'
    | '/hosts'
    | '/mcp'
    | '/ratings'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/admin/reset-password'
    | '/blog/$slug'
    | '/blog/beste-golfbanen-rond-antwerpen'
    | '/courses/$slug'
    | '/ratings/$slug'
    | '/blog/'
    | '/ratings/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/afleveringen'
    | '/contact'
    | '/hosts'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/admin/reset-password'
    | '/blog/$slug'
    | '/blog/beste-golfbanen-rond-antwerpen'
    | '/courses/$slug'
    | '/ratings/$slug'
    | '/blog'
    | '/ratings'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afleveringen'
    | '/blog'
    | '/contact'
    | '/hosts'
    | '/mcp'
    | '/ratings'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/admin/reset-password'
    | '/blog/$slug'
    | '/blog/beste-golfbanen-rond-antwerpen'
    | '/courses/$slug'
    | '/ratings/$slug'
    | '/blog/'
    | '/ratings/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AfleveringenRoute: typeof AfleveringenRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  HostsRoute: typeof HostsRoute
  McpRoute: typeof McpRoute
  RatingsRoute: typeof RatingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afleveringen': {
      id: '/afleveringen'
      path: '/afleveringen'
      fullPath: '/afleveringen'
      preLoaderRoute: typeof AfleveringenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings/': {
      id: '/ratings/'
      path: '/'
      fullPath: '/ratings/'
      preLoaderRoute: typeof RatingsIndexRouteImport
      parentRoute: typeof RatingsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ratings/$slug': {
      id: '/ratings/$slug'
      path: '/$slug'
      fullPath: '/ratings/$slug'
      preLoaderRoute: typeof RatingsSlugRouteImport
      parentRoute: typeof RatingsRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/beste-golfbanen-rond-antwerpen': {
      id: '/blog/beste-golfbanen-rond-antwerpen'
      path: '/beste-golfbanen-rond-antwerpen'
      fullPath: '/blog/beste-golfbanen-rond-antwerpen'
      preLoaderRoute: typeof BlogBesteGolfbanenRondAntwerpenRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogBesteGolfbanenRondAntwerpenRoute: typeof BlogBesteGolfbanenRondAntwerpenRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogBesteGolfbanenRondAntwerpenRoute: BlogBesteGolfbanenRondAntwerpenRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RatingsRouteChildren {
  RatingsSlugRoute: typeof RatingsSlugRoute
  RatingsIndexRoute: typeof RatingsIndexRoute
}

const RatingsRouteChildren: RatingsRouteChildren = {
  RatingsSlugRoute: RatingsSlugRoute,
  RatingsIndexRoute: RatingsIndexRoute,
}

const RatingsRouteWithChildren =
  RatingsRoute._addFileChildren(RatingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AfleveringenRoute: AfleveringenRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  HostsRoute: HostsRoute,
  McpRoute: McpRoute,
  RatingsRoute: RatingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
