/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AfleveringenRouteImport } from './routes/afleveringen'
import { Route as IndexRouteImport } from './routes/index'

const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AfleveringenRoute = AfleveringenRouteImport.update({
  id: '/afleveringen',
  path: '/afleveringen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afleveringen': typeof AfleveringenRoute
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afleveringen': typeof AfleveringenRoute
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afleveringen': typeof AfleveringenRoute
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/afleveringen' | '/contact' | '/hosts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/afleveringen' | '/contact' | '/hosts'
  id: '__root__' | '/' | '/afleveringen' | '/contact' | '/hosts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfleveringenRoute: typeof AfleveringenRoute
  ContactRoute: typeof ContactRoute
  HostsRoute: typeof HostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afleveringen': {
      id: '/afleveringen'
      path: '/afleveringen'
      fullPath: '/afleveringen'
      preLoaderRoute: typeof AfleveringenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfleveringenRoute: AfleveringenRoute,
  ContactRoute: ContactRoute,
  HostsRoute: HostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
