/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AfleveringenRouteImport } from './routes/afleveringen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatingsIndexRouteImport } from './routes/ratings.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RatingsSlugRouteImport } from './routes/ratings.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AfleveringenRoute = AfleveringenRouteImport.update({
  id: '/afleveringen',
  path: '/afleveringen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsIndexRoute = RatingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RatingsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const RatingsSlugRoute = RatingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RatingsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afleveringen': typeof AfleveringenRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/ratings': typeof RatingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ratings/': typeof RatingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afleveringen': typeof AfleveringenRoute
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/ratings': typeof RatingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/afleveringen': typeof AfleveringenRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/hosts': typeof HostsRoute
  '/ratings': typeof RatingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ratings/$slug': typeof RatingsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ratings/': typeof RatingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afleveringen'
    | '/blog'
    | '/contact'
    | '/hosts'
    | '/ratings'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/ratings/$slug'
    | '/blog/'
    | '/ratings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/afleveringen'
    | '/contact'
    | '/hosts'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/ratings/$slug'
    | '/blog'
    | '/ratings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afleveringen'
    | '/blog'
    | '/contact'
    | '/hosts'
    | '/ratings'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/ratings/$slug'
    | '/blog/'
    | '/ratings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AfleveringenRoute: typeof AfleveringenRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  HostsRoute: typeof HostsRoute
  RatingsRoute: typeof RatingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afleveringen': {
      id: '/afleveringen'
      path: '/afleveringen'
      fullPath: '/afleveringen'
      preLoaderRoute: typeof AfleveringenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings/': {
      id: '/ratings/'
      path: '/'
      fullPath: '/ratings/'
      preLoaderRoute: typeof RatingsIndexRouteImport
      parentRoute: typeof RatingsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ratings/$slug': {
      id: '/ratings/$slug'
      path: '/$slug'
      fullPath: '/ratings/$slug'
      preLoaderRoute: typeof RatingsSlugRouteImport
      parentRoute: typeof RatingsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface RatingsRouteChildren {
  RatingsSlugRoute: typeof RatingsSlugRoute
  RatingsIndexRoute: typeof RatingsIndexRoute
}

const RatingsRouteChildren: RatingsRouteChildren = {
  RatingsSlugRoute: RatingsSlugRoute,
  RatingsIndexRoute: RatingsIndexRoute,
}

const RatingsRouteWithChildren =
  RatingsRoute._addFileChildren(RatingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AfleveringenRoute: AfleveringenRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  HostsRoute: HostsRoute,
  RatingsRoute: RatingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
